### ISSUE TITLE
invalid url exception due to whitespace in URL constant

### ISSUE THREAD

**Issue by bawse** [bloXroute-Labs/serum-client-python#137]
https://github.com/bloXroute-Labs/solana-trader-client-python/blob/develop/bxsolana/provider/constants.py#L12

in both http and ws methods:

`return f"{prefix}: //{base}"
`
When attempting to use the API, I get the following exception:
`aiohttp.client_exceptions.InvalidURL: https:///%20//ny.solana.dex.blxrbdn.com/api/v1/trade/submit`

Surely shouldn't have a whitespace? Can this be fixed ASAP, as the provider can't be instantiated with user-provided URL either.

**Comment by atulsriv** [comment]
Can you retest with the latest package (2.1.8 on pypi?) this is fixed
